require('dotenv').config()

const path = require('path')

const express = require('express')
const app = express()

const lti = require('./server/routes/lti')
const users = require('./server/routes/users')
const adminRouter = require('./server/routes/adminRouter')
const scripts = require('./server/routes/scripts')

const pool = require('./util/db')
const sess = require('./util/session')

app.set('trust proxy', 1)

// app.use(cookieParser())
app.use(sess)

// Used to parse request data that sent from web pages in JSON format
app.use(express.json())
app.use(express.urlencoded({ extended: false }))

app.use('/users', users)
app.use('/lti', lti)
app.use('/admin', adminRouter)
app.use('/scripts', scripts)

app.post('/add-selection', (req, res) => {
    console.log(req.body)

    /**
     * Create new entry in 'results' table in database
     * Answer_date is of type 'timestamp with time zone' in PostgreSQL.
     */
    pool.query("INSERT INTO results(session_id, student_id, username, assessment, prompt_image, answer, solution, answer_date) \
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8)", [
        req.sessionID,
        req.session.student_id,
        req.session.username,
        req.body.assessment,
        req.body.promptImage,
        req.body.answer,
        req.body.solution,
        req.body.answerDate,
    ], (err, result) => {
        if (err) throw err;

        res.send('Selection successfully added')
    })
})

// As an admin, unlock the testing section for students to take
app.post('/unlock-testing', function (req, res) {
    pool.query(`UPDATE unlocksections SET unlocked=true WHERE assessment='testing'`, function (err, result) {
        if (err) throw err;
    })
})

// Check if admin has granted access to the testing section
app.get('/unlocked-testing', function (req, res) {
    pool.query(`SELECT unlocked FROM unlocksections WHERE assessment='testing'`, function (err, result) {
        console.log(result.rows[0])

        res.status(200).json(result.rows[0])
    })
})

// Renders HTML file from Simplephy source code
app.use(express.static(path.join(__dirname, 'static')));
app.get('/', function (req, res) {
    res.sendFile(path.join(__dirname, 'static', 'main.html'))
})
app.get('/final-results', function (req, res) {
    res.sendFile(path.join(__dirname, 'static', 'finalResults.html'))
})
app.get('/test-display', function (req, res) {
    res.sendFile(path.join(__dirname, 'static', 'test.html'))
})

// Renders HTML file generated by npm build command
app.use(express.static(path.join(__dirname, 'build')));
app.get(/[a-z]+/, function (req, res) {
    res.sendFile(path.join(__dirname, 'build', 'index.html'));
});

module.exports = app